# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: middleware/mail/v0/mail.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='middleware/mail/v0/mail.proto',
  package='n0stack.mail',
  syntax='proto3',
  serialized_options=_b('Z;github.com/n0stack/n0stack/n0proto/middleware/mail/v0;pmail'),
  serialized_pb=_b('\n\x1dmiddleware/mail/v0/mail.proto\x12\x0cn0stack.mail\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n\x04Mail\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0c\n\x04\x66rom\x18\x03 \x01(\t\x12\n\n\x02to\x18\x04 \x03(\t\x12\n\n\x02\x63\x63\x18\x05 \x03(\t\x12\x31\n\rreceived_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x62lob\x18\x07 \x01(\t\"+\n\x06Thread\x12!\n\x05mails\x18\x01 \x03(\x0b\x32\x12.n0stack.mail.Mail\"\x12\n\x10ListMailsRequest\":\n\x11ListMailsResponse\x12%\n\x07threads\x18\x01 \x03(\x0b\x32\x14.n0stack.mail.Thread\"!\n\x11\x43reateMailRequest\x12\x0c\n\x04\x62lob\x18\x07 \x01(\t2\xa2\x01\n\x0bMailService\x12N\n\tListMails\x12\x1e.n0stack.mail.ListMailsRequest\x1a\x1f.n0stack.mail.ListMailsResponse\"\x00\x12\x43\n\nCreateMail\x12\x1f.n0stack.mail.CreateMailRequest\x1a\x12.n0stack.mail.Mail\"\x00\x42=Z;github.com/n0stack/n0stack/n0proto/middleware/mail/v0;pmailb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_MAIL = _descriptor.Descriptor(
  name='Mail',
  full_name='n0stack.mail.Mail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_id', full_name='n0stack.mail.Mail.message_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subject', full_name='n0stack.mail.Mail.subject', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from', full_name='n0stack.mail.Mail.from', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='n0stack.mail.Mail.to', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cc', full_name='n0stack.mail.Mail.cc', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='received_time', full_name='n0stack.mail.Mail.received_time', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blob', full_name='n0stack.mail.Mail.blob', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=256,
)


_THREAD = _descriptor.Descriptor(
  name='Thread',
  full_name='n0stack.mail.Thread',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mails', full_name='n0stack.mail.Thread.mails', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=301,
)


_LISTMAILSREQUEST = _descriptor.Descriptor(
  name='ListMailsRequest',
  full_name='n0stack.mail.ListMailsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=321,
)


_LISTMAILSRESPONSE = _descriptor.Descriptor(
  name='ListMailsResponse',
  full_name='n0stack.mail.ListMailsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='threads', full_name='n0stack.mail.ListMailsResponse.threads', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=381,
)


_CREATEMAILREQUEST = _descriptor.Descriptor(
  name='CreateMailRequest',
  full_name='n0stack.mail.CreateMailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blob', full_name='n0stack.mail.CreateMailRequest.blob', index=0,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=416,
)

_MAIL.fields_by_name['received_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_THREAD.fields_by_name['mails'].message_type = _MAIL
_LISTMAILSRESPONSE.fields_by_name['threads'].message_type = _THREAD
DESCRIPTOR.message_types_by_name['Mail'] = _MAIL
DESCRIPTOR.message_types_by_name['Thread'] = _THREAD
DESCRIPTOR.message_types_by_name['ListMailsRequest'] = _LISTMAILSREQUEST
DESCRIPTOR.message_types_by_name['ListMailsResponse'] = _LISTMAILSRESPONSE
DESCRIPTOR.message_types_by_name['CreateMailRequest'] = _CREATEMAILREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mail = _reflection.GeneratedProtocolMessageType('Mail', (_message.Message,), dict(
  DESCRIPTOR = _MAIL,
  __module__ = 'middleware.mail.v0.mail_pb2'
  # @@protoc_insertion_point(class_scope:n0stack.mail.Mail)
  ))
_sym_db.RegisterMessage(Mail)

Thread = _reflection.GeneratedProtocolMessageType('Thread', (_message.Message,), dict(
  DESCRIPTOR = _THREAD,
  __module__ = 'middleware.mail.v0.mail_pb2'
  # @@protoc_insertion_point(class_scope:n0stack.mail.Thread)
  ))
_sym_db.RegisterMessage(Thread)

ListMailsRequest = _reflection.GeneratedProtocolMessageType('ListMailsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTMAILSREQUEST,
  __module__ = 'middleware.mail.v0.mail_pb2'
  # @@protoc_insertion_point(class_scope:n0stack.mail.ListMailsRequest)
  ))
_sym_db.RegisterMessage(ListMailsRequest)

ListMailsResponse = _reflection.GeneratedProtocolMessageType('ListMailsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTMAILSRESPONSE,
  __module__ = 'middleware.mail.v0.mail_pb2'
  # @@protoc_insertion_point(class_scope:n0stack.mail.ListMailsResponse)
  ))
_sym_db.RegisterMessage(ListMailsResponse)

CreateMailRequest = _reflection.GeneratedProtocolMessageType('CreateMailRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEMAILREQUEST,
  __module__ = 'middleware.mail.v0.mail_pb2'
  # @@protoc_insertion_point(class_scope:n0stack.mail.CreateMailRequest)
  ))
_sym_db.RegisterMessage(CreateMailRequest)


DESCRIPTOR._options = None

_MAILSERVICE = _descriptor.ServiceDescriptor(
  name='MailService',
  full_name='n0stack.mail.MailService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=419,
  serialized_end=581,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListMails',
    full_name='n0stack.mail.MailService.ListMails',
    index=0,
    containing_service=None,
    input_type=_LISTMAILSREQUEST,
    output_type=_LISTMAILSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateMail',
    full_name='n0stack.mail.MailService.CreateMail',
    index=1,
    containing_service=None,
    input_type=_CREATEMAILREQUEST,
    output_type=_MAIL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAILSERVICE)

DESCRIPTOR.services_by_name['MailService'] = _MAILSERVICE

# @@protoc_insertion_point(module_scope)
