language: python

python:
  - 3.5
  - 3.6

install:
  - pip install flake8
  - pip install mypy lxml
  - pip install git+https://github.com/n0stack/n0library.git@develop

script:
  - flake8 .
  - mypy -p n0core
