version: '3'
services:
  mock_agent:
    image: n0stack/n0core
    command:
      - ./bin/n0core-agent
      - mock
      - --name=mock-node
      - --advertise-address=mock_agent
      - --node-api-endpoint=node:20181
    links:
      - node

  node:
    image: n0stack/n0core
    command:
      - ./bin/n0core-api
      - node
      - --etcd-endpoints=etcd:2379
    ports:
      - "20181:20181"
    links:
      - etcd
  network:
    image: n0stack/n0core
    command:
      - ./bin/n0core-api
      - network
      - --etcd-endpoints=etcd:2379
    ports:
      - "20182:20182"
    links:
      - etcd
  block_storage:
    image: n0stack/n0core
    command:
      - ./bin/n0core-api
      - block_storage
      - --etcd-endpoints=etcd:2379
      - --node-api-endpoint=node:20181
    ports:
      - "20183:20183"
    links:
      - node
      - etcd
  virtual_machine:
    image: n0stack/n0core
    command:
      - ./bin/n0core-api
      - virtual_machine
      - --etcd-endpoints=etcd:2379
      - --node-api-endpoint=node:20181
      - --network-api-endpoint=network:20182
      - --block-storage-api-endpoint=block_storage:20183
    ports:
      - "20184:20184"
    links:
      - node
      - network
      - block_storage
      - etcd
  image:
    image: n0stack/n0core
    command:
      - ./bin/n0core-api
      - image
      - --etcd-endpoints=etcd:2379
      - --block-storage-api-endpoint=block_storage:20183
    ports:
      - "20185:20185"
    links:
      - block_storage
      - etcd

  etcd:
    image: quay.io/coreos/etcd:v3.3
    volumes:
      - ./sandbox/etcd:/etcd_data
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://127.0.0.1:2379,http://127.0.0.1:4001
      - -listen-client-urls
      - http://0.0.0.0:2379,http://0.0.0.0:4001
      - -initial-advertise-peer-urls
      - http://127.0.0.1:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster-token
      - etcd-cluster-1
      - -initial-cluster
      - etcd0=http://127.0.0.1:2380
      # - -initial-cluster-state
      # - new
    ports:
      - "2379:2379"

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: '10.20.180.0/24'
