version: '3'
services:
  mock_agent:
    image: n0stack/n0core
    command:
      - ./bin/n0core
      - mock-agent
      - --name=mock-node
      - --advertise-address=mock_agent
      - --node-api-endpoint=api:20180
    links:
      - api

  api:
    image: n0stack/n0core
    command:
      - ./bin/n0core
      - api
      - --etcd-endpoints=etcd:2379
    ports:
      - "20180:20180"
    links:
      - etcd

  etcd:
    image: quay.io/coreos/etcd:v3.3
    volumes:
      - ./sandbox/etcd:/etcd_data
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://127.0.0.1:2379,http://127.0.0.1:4001
      - -listen-client-urls
      - http://0.0.0.0:2379,http://0.0.0.0:4001
      - -initial-advertise-peer-urls
      - http://127.0.0.1:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster-token
      - etcd-cluster-1
      - -initial-cluster
      - etcd0=http://127.0.0.1:2380
      # - -initial-cluster-state
      # - new
    ports:
      - "2379:2379"

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: '10.20.180.0/24'
