// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provisioning/v0/virtual_machine.proto

package pprovisioning // import "github.com/n0stack/n0stack/n0proto.go/provisioning/v0"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VirtualMachine_VirtualMachineState int32

const (
	// unknown state because failed to connect for scheduled node after RUNNING.
	VirtualMachine_UNKNOWN VirtualMachine_VirtualMachineState = 0
	// working API
	VirtualMachine_PENDING VirtualMachine_VirtualMachineState = 1
	// running vm
	VirtualMachine_RUNNING  VirtualMachine_VirtualMachineState = 2
	VirtualMachine_SHUTDOWN VirtualMachine_VirtualMachineState = 3
	VirtualMachine_PAUSED   VirtualMachine_VirtualMachineState = 4
)

var VirtualMachine_VirtualMachineState_name = map[int32]string{
	0: "UNKNOWN",
	1: "PENDING",
	2: "RUNNING",
	3: "SHUTDOWN",
	4: "PAUSED",
}
var VirtualMachine_VirtualMachineState_value = map[string]int32{
	"UNKNOWN":  0,
	"PENDING":  1,
	"RUNNING":  2,
	"SHUTDOWN": 3,
	"PAUSED":   4,
}

func (x VirtualMachine_VirtualMachineState) String() string {
	return proto.EnumName(VirtualMachine_VirtualMachineState_name, int32(x))
}
func (VirtualMachine_VirtualMachineState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{1, 0}
}

type VirtualMachineNIC struct {
	NetworkName          string            `protobuf:"bytes,1,opt,name=network_name,json=networkName" json:"network_name,omitempty"`
	Annotations          map[string]string `protobuf:"bytes,5,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HardwareAddress      string            `protobuf:"bytes,2,opt,name=hardware_address,json=hardwareAddress" json:"hardware_address,omitempty"`
	Ipv4Address          string            `protobuf:"bytes,3,opt,name=ipv4_address,json=ipv4Address" json:"ipv4_address,omitempty"`
	Ipv6Address          string            `protobuf:"bytes,4,opt,name=ipv6_address,json=ipv6Address" json:"ipv6_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VirtualMachineNIC) Reset()         { *m = VirtualMachineNIC{} }
func (m *VirtualMachineNIC) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineNIC) ProtoMessage()    {}
func (*VirtualMachineNIC) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{0}
}
func (m *VirtualMachineNIC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineNIC.Unmarshal(m, b)
}
func (m *VirtualMachineNIC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineNIC.Marshal(b, m, deterministic)
}
func (dst *VirtualMachineNIC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineNIC.Merge(dst, src)
}
func (m *VirtualMachineNIC) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineNIC.Size(m)
}
func (m *VirtualMachineNIC) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineNIC.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineNIC proto.InternalMessageInfo

func (m *VirtualMachineNIC) GetNetworkName() string {
	if m != nil {
		return m.NetworkName
	}
	return ""
}

func (m *VirtualMachineNIC) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *VirtualMachineNIC) GetHardwareAddress() string {
	if m != nil {
		return m.HardwareAddress
	}
	return ""
}

func (m *VirtualMachineNIC) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *VirtualMachineNIC) GetIpv6Address() string {
	if m != nil {
		return m.Ipv6Address
	}
	return ""
}

type VirtualMachine struct {
	Name                  string                             `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Annotations           map[string]string                  `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestCpuMilliCore   uint32                             `protobuf:"varint,10,opt,name=request_cpu_milli_core,json=requestCpuMilliCore" json:"request_cpu_milli_core,omitempty"`
	LimitCpuMilliCore     uint32                             `protobuf:"varint,11,opt,name=limit_cpu_milli_core,json=limitCpuMilliCore" json:"limit_cpu_milli_core,omitempty"`
	RequestMemoryBytes    uint64                             `protobuf:"varint,12,opt,name=request_memory_bytes,json=requestMemoryBytes" json:"request_memory_bytes,omitempty"`
	LimitMemoryBytes      uint64                             `protobuf:"varint,13,opt,name=limit_memory_bytes,json=limitMemoryBytes" json:"limit_memory_bytes,omitempty"`
	BlockStorageNames     []string                           `protobuf:"bytes,14,rep,name=block_storage_names,json=blockStorageNames" json:"block_storage_names,omitempty"`
	Nics                  []*VirtualMachineNIC               `protobuf:"bytes,15,rep,name=nics" json:"nics,omitempty"`
	Uuid                  string                             `protobuf:"bytes,16,opt,name=uuid" json:"uuid,omitempty"`
	LoginUsername         string                             `protobuf:"bytes,17,opt,name=login_username,json=loginUsername" json:"login_username,omitempty"`
	SshAuthorizedKeys     []string                           `protobuf:"bytes,18,rep,name=ssh_authorized_keys,json=sshAuthorizedKeys" json:"ssh_authorized_keys,omitempty"`
	State                 VirtualMachine_VirtualMachineState `protobuf:"varint,50,opt,name=state,enum=n0stack.provisioning.VirtualMachine_VirtualMachineState" json:"state,omitempty"`
	ComputeNodeName       string                             `protobuf:"bytes,52,opt,name=compute_node_name,json=computeNodeName" json:"compute_node_name,omitempty"`
	ComputeName           string                             `protobuf:"bytes,53,opt,name=compute_name,json=computeName" json:"compute_name,omitempty"`
	NetworkInterfaceNames []string                           `protobuf:"bytes,54,rep,name=network_interface_names,json=networkInterfaceNames" json:"network_interface_names,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                           `json:"-"`
	XXX_unrecognized      []byte                             `json:"-"`
	XXX_sizecache         int32                              `json:"-"`
}

func (m *VirtualMachine) Reset()         { *m = VirtualMachine{} }
func (m *VirtualMachine) String() string { return proto.CompactTextString(m) }
func (*VirtualMachine) ProtoMessage()    {}
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{1}
}
func (m *VirtualMachine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachine.Unmarshal(m, b)
}
func (m *VirtualMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachine.Marshal(b, m, deterministic)
}
func (dst *VirtualMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachine.Merge(dst, src)
}
func (m *VirtualMachine) XXX_Size() int {
	return xxx_messageInfo_VirtualMachine.Size(m)
}
func (m *VirtualMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachine.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachine proto.InternalMessageInfo

func (m *VirtualMachine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualMachine) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *VirtualMachine) GetRequestCpuMilliCore() uint32 {
	if m != nil {
		return m.RequestCpuMilliCore
	}
	return 0
}

func (m *VirtualMachine) GetLimitCpuMilliCore() uint32 {
	if m != nil {
		return m.LimitCpuMilliCore
	}
	return 0
}

func (m *VirtualMachine) GetRequestMemoryBytes() uint64 {
	if m != nil {
		return m.RequestMemoryBytes
	}
	return 0
}

func (m *VirtualMachine) GetLimitMemoryBytes() uint64 {
	if m != nil {
		return m.LimitMemoryBytes
	}
	return 0
}

func (m *VirtualMachine) GetBlockStorageNames() []string {
	if m != nil {
		return m.BlockStorageNames
	}
	return nil
}

func (m *VirtualMachine) GetNics() []*VirtualMachineNIC {
	if m != nil {
		return m.Nics
	}
	return nil
}

func (m *VirtualMachine) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *VirtualMachine) GetLoginUsername() string {
	if m != nil {
		return m.LoginUsername
	}
	return ""
}

func (m *VirtualMachine) GetSshAuthorizedKeys() []string {
	if m != nil {
		return m.SshAuthorizedKeys
	}
	return nil
}

func (m *VirtualMachine) GetState() VirtualMachine_VirtualMachineState {
	if m != nil {
		return m.State
	}
	return VirtualMachine_UNKNOWN
}

func (m *VirtualMachine) GetComputeNodeName() string {
	if m != nil {
		return m.ComputeNodeName
	}
	return ""
}

func (m *VirtualMachine) GetComputeName() string {
	if m != nil {
		return m.ComputeName
	}
	return ""
}

func (m *VirtualMachine) GetNetworkInterfaceNames() []string {
	if m != nil {
		return m.NetworkInterfaceNames
	}
	return nil
}

type CreateVirtualMachineRequest struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Annotations          map[string]string    `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestCpuMilliCore  uint32               `protobuf:"varint,10,opt,name=request_cpu_milli_core,json=requestCpuMilliCore" json:"request_cpu_milli_core,omitempty"`
	LimitCpuMilliCore    uint32               `protobuf:"varint,11,opt,name=limit_cpu_milli_core,json=limitCpuMilliCore" json:"limit_cpu_milli_core,omitempty"`
	RequestMemoryBytes   uint64               `protobuf:"varint,12,opt,name=request_memory_bytes,json=requestMemoryBytes" json:"request_memory_bytes,omitempty"`
	LimitMemoryBytes     uint64               `protobuf:"varint,13,opt,name=limit_memory_bytes,json=limitMemoryBytes" json:"limit_memory_bytes,omitempty"`
	BlockStorageNames    []string             `protobuf:"bytes,14,rep,name=block_storage_names,json=blockStorageNames" json:"block_storage_names,omitempty"`
	Nics                 []*VirtualMachineNIC `protobuf:"bytes,15,rep,name=nics" json:"nics,omitempty"`
	Uuid                 string               `protobuf:"bytes,16,opt,name=uuid" json:"uuid,omitempty"`
	LoginUsername        string               `protobuf:"bytes,17,opt,name=login_username,json=loginUsername" json:"login_username,omitempty"`
	SshAuthorizedKeys    []string             `protobuf:"bytes,18,rep,name=ssh_authorized_keys,json=sshAuthorizedKeys" json:"ssh_authorized_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateVirtualMachineRequest) Reset()         { *m = CreateVirtualMachineRequest{} }
func (m *CreateVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVirtualMachineRequest) ProtoMessage()    {}
func (*CreateVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{2}
}
func (m *CreateVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVirtualMachineRequest.Unmarshal(m, b)
}
func (m *CreateVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (dst *CreateVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVirtualMachineRequest.Merge(dst, src)
}
func (m *CreateVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVirtualMachineRequest.Size(m)
}
func (m *CreateVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVirtualMachineRequest proto.InternalMessageInfo

func (m *CreateVirtualMachineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateVirtualMachineRequest) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *CreateVirtualMachineRequest) GetRequestCpuMilliCore() uint32 {
	if m != nil {
		return m.RequestCpuMilliCore
	}
	return 0
}

func (m *CreateVirtualMachineRequest) GetLimitCpuMilliCore() uint32 {
	if m != nil {
		return m.LimitCpuMilliCore
	}
	return 0
}

func (m *CreateVirtualMachineRequest) GetRequestMemoryBytes() uint64 {
	if m != nil {
		return m.RequestMemoryBytes
	}
	return 0
}

func (m *CreateVirtualMachineRequest) GetLimitMemoryBytes() uint64 {
	if m != nil {
		return m.LimitMemoryBytes
	}
	return 0
}

func (m *CreateVirtualMachineRequest) GetBlockStorageNames() []string {
	if m != nil {
		return m.BlockStorageNames
	}
	return nil
}

func (m *CreateVirtualMachineRequest) GetNics() []*VirtualMachineNIC {
	if m != nil {
		return m.Nics
	}
	return nil
}

func (m *CreateVirtualMachineRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CreateVirtualMachineRequest) GetLoginUsername() string {
	if m != nil {
		return m.LoginUsername
	}
	return ""
}

func (m *CreateVirtualMachineRequest) GetSshAuthorizedKeys() []string {
	if m != nil {
		return m.SshAuthorizedKeys
	}
	return nil
}

type ListVirtualMachinesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVirtualMachinesRequest) Reset()         { *m = ListVirtualMachinesRequest{} }
func (m *ListVirtualMachinesRequest) String() string { return proto.CompactTextString(m) }
func (*ListVirtualMachinesRequest) ProtoMessage()    {}
func (*ListVirtualMachinesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{3}
}
func (m *ListVirtualMachinesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVirtualMachinesRequest.Unmarshal(m, b)
}
func (m *ListVirtualMachinesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVirtualMachinesRequest.Marshal(b, m, deterministic)
}
func (dst *ListVirtualMachinesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVirtualMachinesRequest.Merge(dst, src)
}
func (m *ListVirtualMachinesRequest) XXX_Size() int {
	return xxx_messageInfo_ListVirtualMachinesRequest.Size(m)
}
func (m *ListVirtualMachinesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVirtualMachinesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListVirtualMachinesRequest proto.InternalMessageInfo

type ListVirtualMachinesResponse struct {
	VirtualMachines      []*VirtualMachine `protobuf:"bytes,1,rep,name=virtual_machines,json=virtualMachines" json:"virtual_machines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListVirtualMachinesResponse) Reset()         { *m = ListVirtualMachinesResponse{} }
func (m *ListVirtualMachinesResponse) String() string { return proto.CompactTextString(m) }
func (*ListVirtualMachinesResponse) ProtoMessage()    {}
func (*ListVirtualMachinesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{4}
}
func (m *ListVirtualMachinesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVirtualMachinesResponse.Unmarshal(m, b)
}
func (m *ListVirtualMachinesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVirtualMachinesResponse.Marshal(b, m, deterministic)
}
func (dst *ListVirtualMachinesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVirtualMachinesResponse.Merge(dst, src)
}
func (m *ListVirtualMachinesResponse) XXX_Size() int {
	return xxx_messageInfo_ListVirtualMachinesResponse.Size(m)
}
func (m *ListVirtualMachinesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVirtualMachinesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListVirtualMachinesResponse proto.InternalMessageInfo

func (m *ListVirtualMachinesResponse) GetVirtualMachines() []*VirtualMachine {
	if m != nil {
		return m.VirtualMachines
	}
	return nil
}

type GetVirtualMachineRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVirtualMachineRequest) Reset()         { *m = GetVirtualMachineRequest{} }
func (m *GetVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*GetVirtualMachineRequest) ProtoMessage()    {}
func (*GetVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{5}
}
func (m *GetVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVirtualMachineRequest.Unmarshal(m, b)
}
func (m *GetVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (dst *GetVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVirtualMachineRequest.Merge(dst, src)
}
func (m *GetVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_GetVirtualMachineRequest.Size(m)
}
func (m *GetVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVirtualMachineRequest proto.InternalMessageInfo

func (m *GetVirtualMachineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateVirtualMachineRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Annotations          map[string]string `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestCpuMilliCore  uint32            `protobuf:"varint,10,opt,name=request_cpu_milli_core,json=requestCpuMilliCore" json:"request_cpu_milli_core,omitempty"`
	RequestMemoryBytes   uint64            `protobuf:"varint,12,opt,name=request_memory_bytes,json=requestMemoryBytes" json:"request_memory_bytes,omitempty"`
	BlockStorageNames    []string          `protobuf:"bytes,14,rep,name=block_storage_names,json=blockStorageNames" json:"block_storage_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateVirtualMachineRequest) Reset()         { *m = UpdateVirtualMachineRequest{} }
func (m *UpdateVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateVirtualMachineRequest) ProtoMessage()    {}
func (*UpdateVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{6}
}
func (m *UpdateVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVirtualMachineRequest.Unmarshal(m, b)
}
func (m *UpdateVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVirtualMachineRequest.Merge(dst, src)
}
func (m *UpdateVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateVirtualMachineRequest.Size(m)
}
func (m *UpdateVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVirtualMachineRequest proto.InternalMessageInfo

func (m *UpdateVirtualMachineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateVirtualMachineRequest) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *UpdateVirtualMachineRequest) GetRequestCpuMilliCore() uint32 {
	if m != nil {
		return m.RequestCpuMilliCore
	}
	return 0
}

func (m *UpdateVirtualMachineRequest) GetRequestMemoryBytes() uint64 {
	if m != nil {
		return m.RequestMemoryBytes
	}
	return 0
}

func (m *UpdateVirtualMachineRequest) GetBlockStorageNames() []string {
	if m != nil {
		return m.BlockStorageNames
	}
	return nil
}

type DeleteVirtualMachineRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVirtualMachineRequest) Reset()         { *m = DeleteVirtualMachineRequest{} }
func (m *DeleteVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVirtualMachineRequest) ProtoMessage()    {}
func (*DeleteVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{7}
}
func (m *DeleteVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVirtualMachineRequest.Unmarshal(m, b)
}
func (m *DeleteVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVirtualMachineRequest.Merge(dst, src)
}
func (m *DeleteVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVirtualMachineRequest.Size(m)
}
func (m *DeleteVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVirtualMachineRequest proto.InternalMessageInfo

func (m *DeleteVirtualMachineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BootVirtualMachineRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootVirtualMachineRequest) Reset()         { *m = BootVirtualMachineRequest{} }
func (m *BootVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*BootVirtualMachineRequest) ProtoMessage()    {}
func (*BootVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{8}
}
func (m *BootVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootVirtualMachineRequest.Unmarshal(m, b)
}
func (m *BootVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (dst *BootVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootVirtualMachineRequest.Merge(dst, src)
}
func (m *BootVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_BootVirtualMachineRequest.Size(m)
}
func (m *BootVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BootVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BootVirtualMachineRequest proto.InternalMessageInfo

func (m *BootVirtualMachineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RebootVirtualMachineRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Hard                 bool     `protobuf:"varint,2,opt,name=hard" json:"hard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RebootVirtualMachineRequest) Reset()         { *m = RebootVirtualMachineRequest{} }
func (m *RebootVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*RebootVirtualMachineRequest) ProtoMessage()    {}
func (*RebootVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{9}
}
func (m *RebootVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RebootVirtualMachineRequest.Unmarshal(m, b)
}
func (m *RebootVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RebootVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (dst *RebootVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebootVirtualMachineRequest.Merge(dst, src)
}
func (m *RebootVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_RebootVirtualMachineRequest.Size(m)
}
func (m *RebootVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RebootVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RebootVirtualMachineRequest proto.InternalMessageInfo

func (m *RebootVirtualMachineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RebootVirtualMachineRequest) GetHard() bool {
	if m != nil {
		return m.Hard
	}
	return false
}

type ShutdownVirtualMachineRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Hard                 bool     `protobuf:"varint,2,opt,name=hard" json:"hard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownVirtualMachineRequest) Reset()         { *m = ShutdownVirtualMachineRequest{} }
func (m *ShutdownVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownVirtualMachineRequest) ProtoMessage()    {}
func (*ShutdownVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{10}
}
func (m *ShutdownVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownVirtualMachineRequest.Unmarshal(m, b)
}
func (m *ShutdownVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (dst *ShutdownVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownVirtualMachineRequest.Merge(dst, src)
}
func (m *ShutdownVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownVirtualMachineRequest.Size(m)
}
func (m *ShutdownVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownVirtualMachineRequest proto.InternalMessageInfo

func (m *ShutdownVirtualMachineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShutdownVirtualMachineRequest) GetHard() bool {
	if m != nil {
		return m.Hard
	}
	return false
}

type SaveVirtualMachineRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveVirtualMachineRequest) Reset()         { *m = SaveVirtualMachineRequest{} }
func (m *SaveVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*SaveVirtualMachineRequest) ProtoMessage()    {}
func (*SaveVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{11}
}
func (m *SaveVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveVirtualMachineRequest.Unmarshal(m, b)
}
func (m *SaveVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (dst *SaveVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveVirtualMachineRequest.Merge(dst, src)
}
func (m *SaveVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_SaveVirtualMachineRequest.Size(m)
}
func (m *SaveVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveVirtualMachineRequest proto.InternalMessageInfo

func (m *SaveVirtualMachineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type OpenConsoleRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenConsoleRequest) Reset()         { *m = OpenConsoleRequest{} }
func (m *OpenConsoleRequest) String() string { return proto.CompactTextString(m) }
func (*OpenConsoleRequest) ProtoMessage()    {}
func (*OpenConsoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{12}
}
func (m *OpenConsoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenConsoleRequest.Unmarshal(m, b)
}
func (m *OpenConsoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenConsoleRequest.Marshal(b, m, deterministic)
}
func (dst *OpenConsoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenConsoleRequest.Merge(dst, src)
}
func (m *OpenConsoleRequest) XXX_Size() int {
	return xxx_messageInfo_OpenConsoleRequest.Size(m)
}
func (m *OpenConsoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenConsoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenConsoleRequest proto.InternalMessageInfo

func (m *OpenConsoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type OpenConsoleResponse struct {
	ConsoleUrl           string   `protobuf:"bytes,1,opt,name=console_url,json=consoleUrl" json:"console_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenConsoleResponse) Reset()         { *m = OpenConsoleResponse{} }
func (m *OpenConsoleResponse) String() string { return proto.CompactTextString(m) }
func (*OpenConsoleResponse) ProtoMessage()    {}
func (*OpenConsoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_virtual_machine_4f5882f4445db32a, []int{13}
}
func (m *OpenConsoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenConsoleResponse.Unmarshal(m, b)
}
func (m *OpenConsoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenConsoleResponse.Marshal(b, m, deterministic)
}
func (dst *OpenConsoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenConsoleResponse.Merge(dst, src)
}
func (m *OpenConsoleResponse) XXX_Size() int {
	return xxx_messageInfo_OpenConsoleResponse.Size(m)
}
func (m *OpenConsoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenConsoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenConsoleResponse proto.InternalMessageInfo

func (m *OpenConsoleResponse) GetConsoleUrl() string {
	if m != nil {
		return m.ConsoleUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*VirtualMachineNIC)(nil), "n0stack.provisioning.VirtualMachineNIC")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.provisioning.VirtualMachineNIC.AnnotationsEntry")
	proto.RegisterType((*VirtualMachine)(nil), "n0stack.provisioning.VirtualMachine")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.provisioning.VirtualMachine.AnnotationsEntry")
	proto.RegisterType((*CreateVirtualMachineRequest)(nil), "n0stack.provisioning.CreateVirtualMachineRequest")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.provisioning.CreateVirtualMachineRequest.AnnotationsEntry")
	proto.RegisterType((*ListVirtualMachinesRequest)(nil), "n0stack.provisioning.ListVirtualMachinesRequest")
	proto.RegisterType((*ListVirtualMachinesResponse)(nil), "n0stack.provisioning.ListVirtualMachinesResponse")
	proto.RegisterType((*GetVirtualMachineRequest)(nil), "n0stack.provisioning.GetVirtualMachineRequest")
	proto.RegisterType((*UpdateVirtualMachineRequest)(nil), "n0stack.provisioning.UpdateVirtualMachineRequest")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.provisioning.UpdateVirtualMachineRequest.AnnotationsEntry")
	proto.RegisterType((*DeleteVirtualMachineRequest)(nil), "n0stack.provisioning.DeleteVirtualMachineRequest")
	proto.RegisterType((*BootVirtualMachineRequest)(nil), "n0stack.provisioning.BootVirtualMachineRequest")
	proto.RegisterType((*RebootVirtualMachineRequest)(nil), "n0stack.provisioning.RebootVirtualMachineRequest")
	proto.RegisterType((*ShutdownVirtualMachineRequest)(nil), "n0stack.provisioning.ShutdownVirtualMachineRequest")
	proto.RegisterType((*SaveVirtualMachineRequest)(nil), "n0stack.provisioning.SaveVirtualMachineRequest")
	proto.RegisterType((*OpenConsoleRequest)(nil), "n0stack.provisioning.OpenConsoleRequest")
	proto.RegisterType((*OpenConsoleResponse)(nil), "n0stack.provisioning.OpenConsoleResponse")
	proto.RegisterEnum("n0stack.provisioning.VirtualMachine_VirtualMachineState", VirtualMachine_VirtualMachineState_name, VirtualMachine_VirtualMachineState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VirtualMachineService service

type VirtualMachineServiceClient interface {
	CreateVirtualMachine(ctx context.Context, in *CreateVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error)
	ListVirtualMachines(ctx context.Context, in *ListVirtualMachinesRequest, opts ...grpc.CallOption) (*ListVirtualMachinesResponse, error)
	GetVirtualMachine(ctx context.Context, in *GetVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error)
	UpdateVirtualMachine(ctx context.Context, in *UpdateVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error)
	DeleteVirtualMachine(ctx context.Context, in *DeleteVirtualMachineRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// VM actions
	// -> RUNNING
	BootVirtualMachine(ctx context.Context, in *BootVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error)
	// RUNNING -> RUNNING
	RebootVirtualMachine(ctx context.Context, in *RebootVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error)
	// RUNNING -> SHUTDOWN
	ShutdownVirtualMachine(ctx context.Context, in *ShutdownVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error)
	// RUNNING -> PAUSED
	SaveVirtualMachine(ctx context.Context, in *SaveVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error)
	OpenConsole(ctx context.Context, in *OpenConsoleRequest, opts ...grpc.CallOption) (*OpenConsoleResponse, error)
}

type virtualMachineServiceClient struct {
	cc *grpc.ClientConn
}

func NewVirtualMachineServiceClient(cc *grpc.ClientConn) VirtualMachineServiceClient {
	return &virtualMachineServiceClient{cc}
}

func (c *virtualMachineServiceClient) CreateVirtualMachine(ctx context.Context, in *CreateVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error) {
	out := new(VirtualMachine)
	err := grpc.Invoke(ctx, "/n0stack.provisioning.VirtualMachineService/CreateVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineServiceClient) ListVirtualMachines(ctx context.Context, in *ListVirtualMachinesRequest, opts ...grpc.CallOption) (*ListVirtualMachinesResponse, error) {
	out := new(ListVirtualMachinesResponse)
	err := grpc.Invoke(ctx, "/n0stack.provisioning.VirtualMachineService/ListVirtualMachines", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineServiceClient) GetVirtualMachine(ctx context.Context, in *GetVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error) {
	out := new(VirtualMachine)
	err := grpc.Invoke(ctx, "/n0stack.provisioning.VirtualMachineService/GetVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineServiceClient) UpdateVirtualMachine(ctx context.Context, in *UpdateVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error) {
	out := new(VirtualMachine)
	err := grpc.Invoke(ctx, "/n0stack.provisioning.VirtualMachineService/UpdateVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineServiceClient) DeleteVirtualMachine(ctx context.Context, in *DeleteVirtualMachineRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := grpc.Invoke(ctx, "/n0stack.provisioning.VirtualMachineService/DeleteVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineServiceClient) BootVirtualMachine(ctx context.Context, in *BootVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error) {
	out := new(VirtualMachine)
	err := grpc.Invoke(ctx, "/n0stack.provisioning.VirtualMachineService/BootVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineServiceClient) RebootVirtualMachine(ctx context.Context, in *RebootVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error) {
	out := new(VirtualMachine)
	err := grpc.Invoke(ctx, "/n0stack.provisioning.VirtualMachineService/RebootVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineServiceClient) ShutdownVirtualMachine(ctx context.Context, in *ShutdownVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error) {
	out := new(VirtualMachine)
	err := grpc.Invoke(ctx, "/n0stack.provisioning.VirtualMachineService/ShutdownVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineServiceClient) SaveVirtualMachine(ctx context.Context, in *SaveVirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachine, error) {
	out := new(VirtualMachine)
	err := grpc.Invoke(ctx, "/n0stack.provisioning.VirtualMachineService/SaveVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineServiceClient) OpenConsole(ctx context.Context, in *OpenConsoleRequest, opts ...grpc.CallOption) (*OpenConsoleResponse, error) {
	out := new(OpenConsoleResponse)
	err := grpc.Invoke(ctx, "/n0stack.provisioning.VirtualMachineService/OpenConsole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VirtualMachineService service

type VirtualMachineServiceServer interface {
	CreateVirtualMachine(context.Context, *CreateVirtualMachineRequest) (*VirtualMachine, error)
	ListVirtualMachines(context.Context, *ListVirtualMachinesRequest) (*ListVirtualMachinesResponse, error)
	GetVirtualMachine(context.Context, *GetVirtualMachineRequest) (*VirtualMachine, error)
	UpdateVirtualMachine(context.Context, *UpdateVirtualMachineRequest) (*VirtualMachine, error)
	DeleteVirtualMachine(context.Context, *DeleteVirtualMachineRequest) (*empty.Empty, error)
	// VM actions
	// -> RUNNING
	BootVirtualMachine(context.Context, *BootVirtualMachineRequest) (*VirtualMachine, error)
	// RUNNING -> RUNNING
	RebootVirtualMachine(context.Context, *RebootVirtualMachineRequest) (*VirtualMachine, error)
	// RUNNING -> SHUTDOWN
	ShutdownVirtualMachine(context.Context, *ShutdownVirtualMachineRequest) (*VirtualMachine, error)
	// RUNNING -> PAUSED
	SaveVirtualMachine(context.Context, *SaveVirtualMachineRequest) (*VirtualMachine, error)
	OpenConsole(context.Context, *OpenConsoleRequest) (*OpenConsoleResponse, error)
}

func RegisterVirtualMachineServiceServer(s *grpc.Server, srv VirtualMachineServiceServer) {
	s.RegisterService(&_VirtualMachineService_serviceDesc, srv)
}

func _VirtualMachineService_CreateVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineServiceServer).CreateVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.provisioning.VirtualMachineService/CreateVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineServiceServer).CreateVirtualMachine(ctx, req.(*CreateVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineService_ListVirtualMachines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVirtualMachinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineServiceServer).ListVirtualMachines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.provisioning.VirtualMachineService/ListVirtualMachines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineServiceServer).ListVirtualMachines(ctx, req.(*ListVirtualMachinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineService_GetVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineServiceServer).GetVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.provisioning.VirtualMachineService/GetVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineServiceServer).GetVirtualMachine(ctx, req.(*GetVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineService_UpdateVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineServiceServer).UpdateVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.provisioning.VirtualMachineService/UpdateVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineServiceServer).UpdateVirtualMachine(ctx, req.(*UpdateVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineService_DeleteVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineServiceServer).DeleteVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.provisioning.VirtualMachineService/DeleteVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineServiceServer).DeleteVirtualMachine(ctx, req.(*DeleteVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineService_BootVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineServiceServer).BootVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.provisioning.VirtualMachineService/BootVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineServiceServer).BootVirtualMachine(ctx, req.(*BootVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineService_RebootVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineServiceServer).RebootVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.provisioning.VirtualMachineService/RebootVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineServiceServer).RebootVirtualMachine(ctx, req.(*RebootVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineService_ShutdownVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineServiceServer).ShutdownVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.provisioning.VirtualMachineService/ShutdownVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineServiceServer).ShutdownVirtualMachine(ctx, req.(*ShutdownVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineService_SaveVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineServiceServer).SaveVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.provisioning.VirtualMachineService/SaveVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineServiceServer).SaveVirtualMachine(ctx, req.(*SaveVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineService_OpenConsole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenConsoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineServiceServer).OpenConsole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.provisioning.VirtualMachineService/OpenConsole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineServiceServer).OpenConsole(ctx, req.(*OpenConsoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VirtualMachineService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "n0stack.provisioning.VirtualMachineService",
	HandlerType: (*VirtualMachineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVirtualMachine",
			Handler:    _VirtualMachineService_CreateVirtualMachine_Handler,
		},
		{
			MethodName: "ListVirtualMachines",
			Handler:    _VirtualMachineService_ListVirtualMachines_Handler,
		},
		{
			MethodName: "GetVirtualMachine",
			Handler:    _VirtualMachineService_GetVirtualMachine_Handler,
		},
		{
			MethodName: "UpdateVirtualMachine",
			Handler:    _VirtualMachineService_UpdateVirtualMachine_Handler,
		},
		{
			MethodName: "DeleteVirtualMachine",
			Handler:    _VirtualMachineService_DeleteVirtualMachine_Handler,
		},
		{
			MethodName: "BootVirtualMachine",
			Handler:    _VirtualMachineService_BootVirtualMachine_Handler,
		},
		{
			MethodName: "RebootVirtualMachine",
			Handler:    _VirtualMachineService_RebootVirtualMachine_Handler,
		},
		{
			MethodName: "ShutdownVirtualMachine",
			Handler:    _VirtualMachineService_ShutdownVirtualMachine_Handler,
		},
		{
			MethodName: "SaveVirtualMachine",
			Handler:    _VirtualMachineService_SaveVirtualMachine_Handler,
		},
		{
			MethodName: "OpenConsole",
			Handler:    _VirtualMachineService_OpenConsole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provisioning/v0/virtual_machine.proto",
}

func init() {
	proto.RegisterFile("provisioning/v0/virtual_machine.proto", fileDescriptor_virtual_machine_4f5882f4445db32a)
}

var fileDescriptor_virtual_machine_4f5882f4445db32a = []byte{
	// 1052 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xb6, 0x2c, 0x25, 0x71, 0x46, 0xfe, 0x91, 0xd6, 0x8a, 0xcb, 0x48, 0x2d, 0xaa, 0x12, 0x0d,
	0xaa, 0x14, 0x05, 0xe5, 0x9f, 0xc4, 0x08, 0x1a, 0xa0, 0x80, 0x2d, 0x0b, 0xae, 0x91, 0x9a, 0x0e,
	0xa8, 0x2a, 0x01, 0x72, 0x21, 0x28, 0x72, 0x23, 0x11, 0x22, 0xb9, 0xf4, 0xee, 0x52, 0x86, 0x8a,
	0x3e, 0x41, 0x5f, 0xab, 0xef, 0xd3, 0x5b, 0x4f, 0xbd, 0x14, 0xbb, 0xa4, 0x5c, 0xc9, 0xa2, 0x54,
	0x0a, 0x46, 0x0e, 0x05, 0x7a, 0x32, 0x77, 0xe6, 0x9b, 0xd9, 0xd9, 0x6f, 0xe7, 0x1b, 0x9a, 0x82,
	0x67, 0x21, 0x25, 0x23, 0x97, 0xb9, 0x24, 0x70, 0x83, 0x7e, 0x73, 0xb4, 0xdf, 0x1c, 0xb9, 0x94,
	0x47, 0x96, 0x67, 0xfa, 0x96, 0x3d, 0x70, 0x03, 0xac, 0x85, 0x94, 0x70, 0x82, 0x2a, 0xc1, 0x3e,
	0xe3, 0x96, 0x3d, 0xd4, 0xa6, 0xe1, 0xd5, 0x5a, 0x9f, 0x90, 0xbe, 0x87, 0x9b, 0x12, 0xd3, 0x8b,
	0x3e, 0x36, 0xb1, 0x1f, 0xf2, 0x71, 0x1c, 0xa2, 0xfe, 0xbe, 0x0e, 0xe5, 0x77, 0x71, 0xb2, 0xcb,
	0x38, 0x97, 0x7e, 0xd1, 0x42, 0x5f, 0xc1, 0x66, 0x80, 0xf9, 0x0d, 0xa1, 0x43, 0x33, 0xb0, 0x7c,
	0xac, 0xe4, 0xea, 0xb9, 0xc6, 0x63, 0xa3, 0x98, 0xd8, 0x74, 0xcb, 0xc7, 0xe8, 0x03, 0x14, 0xad,
	0x20, 0x20, 0xdc, 0xe2, 0x2e, 0x09, 0x98, 0xf2, 0xa0, 0x9e, 0x6f, 0x14, 0x0f, 0x5f, 0x69, 0x69,
	0x15, 0x68, 0x73, 0x1b, 0x68, 0x27, 0xff, 0x84, 0xb6, 0x03, 0x4e, 0xc7, 0xc6, 0x74, 0x32, 0xf4,
	0x1c, 0x4a, 0x03, 0x8b, 0x3a, 0x37, 0x16, 0xc5, 0xa6, 0xe5, 0x38, 0x14, 0x33, 0xa6, 0xac, 0xcb,
	0x12, 0x76, 0x26, 0xf6, 0x93, 0xd8, 0x2c, 0x2a, 0x75, 0xc3, 0xd1, 0x8b, 0x5b, 0x58, 0x3e, 0xae,
	0x54, 0xd8, 0x66, 0x21, 0xc7, 0xb7, 0x90, 0xc2, 0x2d, 0xe4, 0x38, 0x81, 0x54, 0x7f, 0x80, 0xd2,
	0xdd, 0x8a, 0x50, 0x09, 0xf2, 0x43, 0x3c, 0x4e, 0x8e, 0x2e, 0x1e, 0x51, 0x05, 0x1e, 0x8c, 0x2c,
	0x2f, 0xc2, 0x49, 0x2d, 0xf1, 0xe2, 0xfb, 0xf5, 0x57, 0x39, 0xf5, 0xb7, 0x47, 0xb0, 0x3d, 0x7b,
	0x48, 0x84, 0xa0, 0x30, 0x45, 0x9d, 0x7c, 0x46, 0xef, 0x67, 0x39, 0xcb, 0x4b, 0xce, 0x5e, 0x66,
	0xe1, 0xec, 0x5f, 0x08, 0x3b, 0x82, 0x3d, 0x8a, 0xaf, 0x23, 0xcc, 0xb8, 0x69, 0x87, 0x91, 0xe9,
	0xbb, 0x9e, 0xe7, 0x9a, 0x36, 0xa1, 0x58, 0x81, 0x7a, 0xae, 0xb1, 0x65, 0xec, 0x26, 0xde, 0x56,
	0x18, 0x5d, 0x0a, 0x5f, 0x8b, 0x50, 0x8c, 0x9a, 0x50, 0xf1, 0x5c, 0xdf, 0x9d, 0x0b, 0x29, 0xca,
	0x90, 0xb2, 0xf4, 0xcd, 0x04, 0xec, 0x43, 0x65, 0xb2, 0x8b, 0x8f, 0x7d, 0x42, 0xc7, 0x66, 0x6f,
	0xcc, 0x31, 0x53, 0x36, 0xeb, 0xb9, 0x46, 0xc1, 0x40, 0x89, 0xef, 0x52, 0xba, 0x4e, 0x85, 0x07,
	0x7d, 0x07, 0x28, 0xde, 0x62, 0x06, 0xbf, 0x25, 0xf1, 0x25, 0xe9, 0x99, 0x46, 0x6b, 0xb0, 0xdb,
	0xf3, 0x88, 0x3d, 0x34, 0x19, 0x27, 0xd4, 0xea, 0x63, 0xd9, 0x7b, 0x4c, 0xd9, 0xae, 0xe7, 0x1b,
	0x8f, 0x8d, 0xb2, 0x74, 0x75, 0x62, 0x8f, 0xe8, 0x40, 0x86, 0x5e, 0x43, 0x21, 0x70, 0x6d, 0xa6,
	0xec, 0x48, 0x1e, 0xbf, 0xc9, 0xd8, 0x7b, 0x86, 0x0c, 0x12, 0xf7, 0x13, 0x45, 0xae, 0xa3, 0x94,
	0xe2, 0xfb, 0x11, 0xcf, 0xe8, 0x19, 0x6c, 0x7b, 0xa4, 0xef, 0x06, 0x66, 0xc4, 0x30, 0x95, 0xb7,
	0x57, 0x96, 0xde, 0x2d, 0x69, 0xed, 0x26, 0x46, 0x51, 0x27, 0x63, 0x03, 0xd3, 0x8a, 0xf8, 0x80,
	0x50, 0xf7, 0x17, 0xec, 0x98, 0x43, 0x3c, 0x66, 0x0a, 0x8a, 0xeb, 0x64, 0x6c, 0x70, 0x72, 0xeb,
	0x79, 0x83, 0xc7, 0x0c, 0xe9, 0xf0, 0x80, 0x71, 0x8b, 0x63, 0xe5, 0xb0, 0x9e, 0x6b, 0x6c, 0x67,
	0x13, 0xc9, 0x9d, 0x65, 0x47, 0xc4, 0x1b, 0x71, 0x1a, 0xf4, 0x2d, 0x94, 0x6d, 0xe2, 0x87, 0x11,
	0xc7, 0x66, 0x40, 0x9c, 0x98, 0x26, 0xe5, 0x45, 0xac, 0x8f, 0xc4, 0xa1, 0x13, 0x47, 0x92, 0x24,
	0x9a, 0xff, 0x16, 0x2b, 0x60, 0x2f, 0xe3, 0xe6, 0x9f, 0xc0, 0x04, 0xe4, 0x18, 0x3e, 0x9b, 0x88,
	0xdd, 0x0d, 0x38, 0xa6, 0x1f, 0x2d, 0x7b, 0x42, 0xfd, 0xb1, 0x3c, 0xd2, 0x93, 0xc4, 0x7d, 0x31,
	0xf1, 0x4a, 0xfa, 0xef, 0x2d, 0x9a, 0x77, 0xb0, 0x9b, 0x72, 0x48, 0x54, 0x84, 0x47, 0x5d, 0xfd,
	0x8d, 0x7e, 0xf5, 0x5e, 0x2f, 0xad, 0x89, 0xc5, 0xdb, 0xb6, 0x7e, 0x76, 0xa1, 0x9f, 0x97, 0x72,
	0x62, 0x61, 0x74, 0x75, 0x5d, 0x2c, 0xd6, 0xd1, 0x26, 0x6c, 0x74, 0x7e, 0xec, 0xfe, 0x7c, 0x26,
	0x70, 0x79, 0x04, 0xf0, 0xf0, 0xed, 0x49, 0xb7, 0xd3, 0x3e, 0x2b, 0x15, 0xd4, 0x3f, 0x0b, 0x50,
	0x6b, 0x51, 0x6c, 0x71, 0x3c, 0x9b, 0xde, 0x88, 0xfb, 0x33, 0x55, 0x99, 0x4e, 0x9a, 0x32, 0x4f,
	0xd3, 0x2f, 0x6a, 0x49, 0xee, 0xff, 0x65, 0xfa, 0xdf, 0x95, 0xe9, 0xbd, 0xfb, 0xf9, 0x73, 0xa8,
	0xfe, 0xe4, 0x32, 0x3e, 0x7b, 0x12, 0x96, 0x74, 0x86, 0x1a, 0x40, 0x2d, 0xd5, 0xcb, 0x42, 0x12,
	0x30, 0x8c, 0xae, 0xa0, 0x74, 0xe7, 0x9d, 0xce, 0x94, 0x9c, 0x24, 0xec, 0xeb, 0x2c, 0x84, 0x19,
	0x3b, 0xa3, 0xd9, 0xc4, 0xaa, 0x06, 0xca, 0x39, 0xe6, 0x99, 0x15, 0xa0, 0xfe, 0xb1, 0x0e, 0xb5,
	0x6e, 0xe8, 0x7c, 0x32, 0xd5, 0x2c, 0xc9, 0xfd, 0x29, 0x54, 0xb3, 0xba, 0x08, 0x56, 0x6c, 0xeb,
	0x7b, 0xb7, 0xcb, 0x01, 0xd4, 0xce, 0xb0, 0x87, 0x57, 0xe0, 0x5b, 0x6d, 0xc2, 0xd3, 0x53, 0x42,
	0x56, 0xb8, 0xd4, 0x36, 0xd4, 0x0c, 0xdc, 0x5b, 0x25, 0x44, 0xd8, 0xc4, 0xff, 0x58, 0xb2, 0xde,
	0x0d, 0x43, 0x3e, 0xab, 0xe7, 0xf0, 0x45, 0x67, 0x10, 0x71, 0x87, 0xdc, 0x04, 0xf7, 0x4b, 0xd4,
	0x84, 0xa7, 0x1d, 0x6b, 0xb4, 0xc2, 0x89, 0x1b, 0x80, 0xae, 0x42, 0x1c, 0xb4, 0x48, 0xc0, 0x88,
	0xb7, 0x14, 0x79, 0x0c, 0xbb, 0x33, 0xc8, 0x44, 0x57, 0x5f, 0x42, 0xd1, 0x8e, 0x4d, 0x66, 0x44,
	0xbd, 0x24, 0x02, 0x12, 0x53, 0x97, 0x7a, 0x87, 0x7f, 0x6d, 0xc0, 0x93, 0x3b, 0xaf, 0x21, 0x4c,
	0x47, 0xae, 0x8d, 0xd1, 0x35, 0x54, 0xd2, 0x46, 0x3d, 0x3a, 0x58, 0xf9, 0xb5, 0x50, 0xcd, 0xa4,
	0x61, 0x75, 0x0d, 0xfd, 0x0a, 0xbb, 0x29, 0x43, 0x02, 0xed, 0xa7, 0x87, 0x2f, 0x9e, 0x36, 0xd5,
	0x83, 0x15, 0x22, 0x62, 0xa6, 0xd4, 0x35, 0x34, 0x84, 0xf2, 0xdc, 0xc8, 0x40, 0x5a, 0x7a, 0xa6,
	0x45, 0xb3, 0x25, 0xf3, 0x51, 0xaf, 0xa1, 0x92, 0x36, 0x12, 0x16, 0xb1, 0xbb, 0x64, 0x7c, 0x64,
	0xde, 0xd2, 0x86, 0x4a, 0x9a, 0xe2, 0x16, 0x6d, 0xb9, 0x44, 0x9d, 0xd5, 0x3d, 0x2d, 0xfe, 0xa8,
	0xd2, 0x26, 0x1f, 0x55, 0x5a, 0x5b, 0x7c, 0x54, 0xa9, 0x6b, 0xc8, 0x07, 0x34, 0xaf, 0x51, 0xd4,
	0x4c, 0xdf, 0x62, 0xa1, 0x9a, 0x57, 0xa1, 0x31, 0x4d, 0xe1, 0x8b, 0xce, 0xb4, 0x64, 0x1a, 0x64,
	0xde, 0x32, 0x82, 0xbd, 0xf4, 0x69, 0x80, 0x8e, 0xd2, 0x33, 0x2c, 0x9d, 0x1d, 0x99, 0xb7, 0xf5,
	0x01, 0xcd, 0xcf, 0x8e, 0x45, 0xc4, 0x2e, 0x9c, 0x32, 0x99, 0xb7, 0x73, 0xa0, 0x38, 0x35, 0x4f,
	0x50, 0x23, 0x3d, 0x6c, 0x7e, 0x38, 0x55, 0x9f, 0x67, 0x40, 0x4e, 0x24, 0x77, 0xda, 0xfe, 0xd0,
	0xea, 0xbb, 0x7c, 0x10, 0xf5, 0x34, 0x9b, 0xf8, 0xcd, 0x24, 0x70, 0xea, 0xaf, 0x6c, 0x2f, 0xad,
	0x4f, 0x9a, 0x77, 0x7e, 0x00, 0x78, 0x1d, 0x4e, 0x1b, 0x7a, 0x0f, 0x25, 0xee, 0xe8, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf2, 0x55, 0x62, 0xca, 0x28, 0x10, 0x00, 0x00,
}
