#!/usr/bin/env python
# -*- coding: utf-8 -*-


from n0library.arguments.common import CommonArguments
from n0core.processor.agent import Agent
from n0core.gateway.pulsar import Pulsar
from n0core.target.network import Network
from n0core.target.network.bridge.flat import Flat


def main():
    argparser = CommonArguments(
        description="Process of n0stack porter type flat"
    )
    argparser.add_argument("--interface-name",
                           type=str,
                           default=None,
                           help="Set interface name to create br-flat automatically")
    args = argparser.parse_args()

    # target
    f = Flat(args.interface_name)
    n = Network(f)
    p = Pulsar(args.mq_url, "aggregater")

    a = Agent(n, ["resource/network", "resource/port"], p)
    a.run()  # わからん


if __name__ == "__main__":
    main()
