version: 2
jobs:
  versioning:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    master: master
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b5:40:bd:39:2d:5b:2d:2c:f0:98:98:22:2d:97:56:b9"
      - run:
          name: git-configure
          command: |
            git config --global user.name "n0stack bot"
            git config --global user.email "h-otter@outlook.jp"
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run:
          name: increment version
          command: make increment
      - run:
          name: push
          command: |
            git add -f VERSION
            git commit -m "increment version to $(cat VERSION) [skip ci]"
            git push origin master
      # push n0core and n0cli to GitHub releases
      - run:
          name: install ghr
          command: |
            rm go.sum  # TODO: Failするので暫定処置
            GO111MODULE=on make vendor
            make release-to-github
workflows:
  version: 2
  all:
    jobs:
      # - build:
      # - test:
      #     requires:
      #       - build
      - versioning:
          # requires:
          #   - test
          filters:
            branches:
              only: master
