# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: create_vm_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='create_vm_request.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x63reate_vm_request.proto\"\x11\n\x0f\x43reateVMRequestb\x06proto3')
)




_CREATEVMREQUEST = _descriptor.Descriptor(
  name='CreateVMRequest',
  full_name='CreateVMRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=44,
)

DESCRIPTOR.message_types_by_name['CreateVMRequest'] = _CREATEVMREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateVMRequest = _reflection.GeneratedProtocolMessageType('CreateVMRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEVMREQUEST,
  __module__ = 'create_vm_request_pb2'
  # @@protoc_insertion_point(class_scope:CreateVMRequest)
  ))
_sym_db.RegisterMessage(CreateVMRequest)


# @@protoc_insertion_point(module_scope)
