# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: migrate_vm_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='migrate_vm_request.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18migrate_vm_request.proto\"R\n\x10MigrateVMRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x10\n\x08src_path\x18\x03 \x01(\t\x12\x10\n\x08\x64st_path\x18\x04 \x01(\tb\x06proto3')
)




_MIGRATEVMREQUEST = _descriptor.Descriptor(
  name='MigrateVMRequest',
  full_name='MigrateVMRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MigrateVMRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host', full_name='MigrateVMRequest.host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_path', full_name='MigrateVMRequest.src_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dst_path', full_name='MigrateVMRequest.dst_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['MigrateVMRequest'] = _MIGRATEVMREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MigrateVMRequest = _reflection.GeneratedProtocolMessageType('MigrateVMRequest', (_message.Message,), dict(
  DESCRIPTOR = _MIGRATEVMREQUEST,
  __module__ = 'migrate_vm_request_pb2'
  # @@protoc_insertion_point(class_scope:MigrateVMRequest)
  ))
_sym_db.RegisterMessage(MigrateVMRequest)


# @@protoc_insertion_point(module_scope)
