# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_vm_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='update_vm_request.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x17update_vm_request.proto\"\x11\n\x0fUpdateVMRequestb\x06proto3')
)




_UPDATEVMREQUEST = _descriptor.Descriptor(
  name='UpdateVMRequest',
  full_name='UpdateVMRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=44,
)

DESCRIPTOR.message_types_by_name['UpdateVMRequest'] = _UPDATEVMREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateVMRequest = _reflection.GeneratedProtocolMessageType('UpdateVMRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEVMREQUEST,
  __module__ = 'update_vm_request_pb2'
  # @@protoc_insertion_point(class_scope:UpdateVMRequest)
  ))
_sym_db.RegisterMessage(UpdateVMRequest)


# @@protoc_insertion_point(module_scope)
