// Code generated by "standard_api"; DO NOT EDIT.

package anetwork

import (
	"context"

	"github.com/golang/protobuf/proto"
	"n0st.ac/n0stack/n0core/pkg/datastore"
	grpcutil "n0st.ac/n0stack/n0core/pkg/util/grpc"
	pinfrastructure "n0st.ac/n0stack/n0proto.go/infrastructure/v0"
	"n0st.ac/n0stack/n0proto.go/pkg/transaction"
	"google.golang.org/grpc/codes"
)

func ListNetworks(ctx context.Context, req *pinfrastructure.ListNetworksRequest, ds datastore.Datastore) (*pinfrastructure.ListNetworksResponse, error) {
	res := &pinfrastructure.ListNetworksResponse{}
	f := func(s int) []proto.Message {
		res.Networks = make([]*pinfrastructure.Network, s)
		for i := range res.Networks {
			res.Networks[i] = &pinfrastructure.Network{}
		}

		m := make([]proto.Message, s)
		for i, v := range res.Networks {
			m[i] = v
		}

		return m
	}

	if err := ds.List(f); err != nil {
		return nil, grpcutil.Errorf(codes.Internal, "Failed to list from db, please retry or contact for the administrator of this cluster")
	}
	if len(res.Networks) == 0 {
		return nil, grpcutil.Errorf(codes.NotFound, "")
	}

	return res, nil
}

func GetNetwork(ctx context.Context, req *pinfrastructure.GetNetworkRequest, ds datastore.Datastore) (*pinfrastructure.Network, error) {
	resourse := &pinfrastructure.Network{}
	if err := ds.Get(req.Name, resourse); err != nil {
		if datastore.IsNotFound(err) {
			return nil, grpcutil.Errorf(codes.NotFound, err.Error())
		}

		return nil, grpcutil.Errorf(codes.Internal, datastore.DefaultErrorMessage(err))
	}

	return resourse, nil
}

func GetAndPendExistingNetwork(tx *transaction.Transaction, ds datastore.Datastore, name string) (*pinfrastructure.Network, error) {
	resource := &pinfrastructure.Network{}
	if err := ds.Get(name, resource); err != nil {
		if datastore.IsNotFound(err) {
			return nil, grpcutil.Errorf(codes.NotFound, err.Error())
		}

		return nil, grpcutil.Errorf(codes.Internal, datastore.DefaultErrorMessage(err))
	}

	if resource.State == pinfrastructure.Network_PENDING {
		return nil, grpcutil.Errorf(codes.FailedPrecondition, "Network %s is pending", name)
	}

	current := resource.State
	resource.State = pinfrastructure.Network_PENDING
	if err := ApplyNetwork(ds, resource); err != nil {
		return nil, err
	}
	resource.State = current
	tx.PushRollback("free optimistic lock", func() error {
		resource.State = current
		return ds.Apply(resource.Name, resource)
	})

	return resource, nil
}

func PendNewNetwork(tx *transaction.Transaction, ds datastore.Datastore, name string) error {
	resource := &pinfrastructure.Network{}
	if err := ds.Get(name, resource); err == nil {
		return grpcutil.Errorf(codes.AlreadyExists, "Network %s is already exists", name)
	} else if !datastore.IsNotFound(err) {
		return grpcutil.Errorf(codes.Internal, datastore.DefaultErrorMessage(err))
	}

	resource.Name = name
	resource.State = pinfrastructure.Network_PENDING
	if err := ApplyNetwork(ds, resource); err != nil {
		return err
	}
	tx.PushRollback("free optimistic lock", func() error {
		return ds.Delete(name)
	})

	return nil
}

func DeleteNetwork(ds datastore.Datastore, name string) error {
	if err := ds.Delete(name); err != nil {
		return grpcutil.Errorf(codes.Internal, "failed to delete Network %s from db: err='%s'", name, err.Error())
	}

	return nil
}

func ApplyNetwork(ds datastore.Datastore, resource *pinfrastructure.Network) error {
	if err := ds.Apply(resource.Name, resource); err != nil {
		return grpcutil.Errorf(codes.Internal, "failed to apply Network %s to db: err='%s'", resource.Name, err.Error())
	}

	return nil
}
