# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: delete_vm_snapshot_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='delete_vm_snapshot_request.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n delete_vm_snapshot_request.proto\"\x19\n\x17\x44\x65leteVMSnapshotRequestb\x06proto3')
)




_DELETEVMSNAPSHOTREQUEST = _descriptor.Descriptor(
  name='DeleteVMSnapshotRequest',
  full_name='DeleteVMSnapshotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['DeleteVMSnapshotRequest'] = _DELETEVMSNAPSHOTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeleteVMSnapshotRequest = _reflection.GeneratedProtocolMessageType('DeleteVMSnapshotRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEVMSNAPSHOTREQUEST,
  __module__ = 'delete_vm_snapshot_request_pb2'
  # @@protoc_insertion_point(class_scope:DeleteVMSnapshotRequest)
  ))
_sym_db.RegisterMessage(DeleteVMSnapshotRequest)


# @@protoc_insertion_point(module_scope)
