// Code generated by protoc-gen-go. DO NOT EDIT.
// source: n0stack/iam/v1alpha/project.proto

package piam

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProjectMembership int32

const (
	ProjectMembership_PROJECT_MEMBERSHIP_UNSPECIFIED ProjectMembership = 0
	// Owners have all of permissions.
	ProjectMembership_OWNER ProjectMembership = 1
	// Members have only assined permissions by Roles.
	ProjectMembership_MEMBER ProjectMembership = 2
)

var ProjectMembership_name = map[int32]string{
	0: "PROJECT_MEMBERSHIP_UNSPECIFIED",
	1: "OWNER",
	2: "MEMBER",
}

var ProjectMembership_value = map[string]int32{
	"PROJECT_MEMBERSHIP_UNSPECIFIED": 0,
	"OWNER":                          1,
	"MEMBER":                         2,
}

func (x ProjectMembership) String() string {
	return proto.EnumName(ProjectMembership_name, int32(x))
}

func (ProjectMembership) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_165db4196db99c73, []int{0}
}

type Project struct {
	// Name is a unique field.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Annotations can store metadata used by the system for control.
	// In particular, implementation-dependent fields that can not be set as protobuf fields are targeted.
	// The control specified by n0stack may delete metadata specified by the user.
	Annotations map[string]string `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Labels stores user-defined metadata.
	// The n0stack system must not rewrite this value.
	Labels               map[string]string            `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DisplayName          string                       `protobuf:"bytes,9,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Membership           map[string]ProjectMembership `protobuf:"bytes,32,rep,name=membership,proto3" json:"membership,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=n0stack.iam.v1alpha.ProjectMembership"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_165db4196db99c73, []int{0}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Project) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Project) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Project) GetMembership() map[string]ProjectMembership {
	if m != nil {
		return m.Membership
	}
	return nil
}

type ListProjectsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectsRequest) Reset()         { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()    {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_165db4196db99c73, []int{1}
}

func (m *ListProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsRequest.Unmarshal(m, b)
}
func (m *ListProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsRequest.Marshal(b, m, deterministic)
}
func (m *ListProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsRequest.Merge(m, src)
}
func (m *ListProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectsRequest.Size(m)
}
func (m *ListProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsRequest proto.InternalMessageInfo

type ListProjectsResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProjectsResponse) Reset()         { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()    {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_165db4196db99c73, []int{2}
}

func (m *ListProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsResponse.Unmarshal(m, b)
}
func (m *ListProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsResponse.Marshal(b, m, deterministic)
}
func (m *ListProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsResponse.Merge(m, src)
}
func (m *ListProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectsResponse.Size(m)
}
func (m *ListProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsResponse proto.InternalMessageInfo

func (m *ListProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type GetProjectRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectRequest) Reset()         { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()    {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_165db4196db99c73, []int{3}
}

func (m *GetProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectRequest.Unmarshal(m, b)
}
func (m *GetProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectRequest.Merge(m, src)
}
func (m *GetProjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectRequest.Size(m)
}
func (m *GetProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectRequest proto.InternalMessageInfo

func (m *GetProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateProjectRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_165db4196db99c73, []int{4}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type UpdateProjectRequest struct {
	Project              *Project              `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateProjectRequest) Reset()         { *m = UpdateProjectRequest{} }
func (m *UpdateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectRequest) ProtoMessage()    {}
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_165db4196db99c73, []int{5}
}

func (m *UpdateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectRequest.Unmarshal(m, b)
}
func (m *UpdateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectRequest.Merge(m, src)
}
func (m *UpdateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectRequest.Size(m)
}
func (m *UpdateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectRequest proto.InternalMessageInfo

func (m *UpdateProjectRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *UpdateProjectRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteProjectRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProjectRequest) Reset()         { *m = DeleteProjectRequest{} }
func (m *DeleteProjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProjectRequest) ProtoMessage()    {}
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_165db4196db99c73, []int{6}
}

func (m *DeleteProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProjectRequest.Unmarshal(m, b)
}
func (m *DeleteProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProjectRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProjectRequest.Merge(m, src)
}
func (m *DeleteProjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProjectRequest.Size(m)
}
func (m *DeleteProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProjectRequest proto.InternalMessageInfo

func (m *DeleteProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddProjectMembershipRequest struct {
	ProjectName          string            `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	UserName             string            `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Membership           ProjectMembership `protobuf:"varint,3,opt,name=membership,proto3,enum=n0stack.iam.v1alpha.ProjectMembership" json:"membership,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddProjectMembershipRequest) Reset()         { *m = AddProjectMembershipRequest{} }
func (m *AddProjectMembershipRequest) String() string { return proto.CompactTextString(m) }
func (*AddProjectMembershipRequest) ProtoMessage()    {}
func (*AddProjectMembershipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_165db4196db99c73, []int{7}
}

func (m *AddProjectMembershipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProjectMembershipRequest.Unmarshal(m, b)
}
func (m *AddProjectMembershipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProjectMembershipRequest.Marshal(b, m, deterministic)
}
func (m *AddProjectMembershipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProjectMembershipRequest.Merge(m, src)
}
func (m *AddProjectMembershipRequest) XXX_Size() int {
	return xxx_messageInfo_AddProjectMembershipRequest.Size(m)
}
func (m *AddProjectMembershipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProjectMembershipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProjectMembershipRequest proto.InternalMessageInfo

func (m *AddProjectMembershipRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *AddProjectMembershipRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AddProjectMembershipRequest) GetMembership() ProjectMembership {
	if m != nil {
		return m.Membership
	}
	return ProjectMembership_PROJECT_MEMBERSHIP_UNSPECIFIED
}

type DeleteProjectMembershipRequest struct {
	ProjectName          string   `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProjectMembershipRequest) Reset()         { *m = DeleteProjectMembershipRequest{} }
func (m *DeleteProjectMembershipRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProjectMembershipRequest) ProtoMessage()    {}
func (*DeleteProjectMembershipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_165db4196db99c73, []int{8}
}

func (m *DeleteProjectMembershipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProjectMembershipRequest.Unmarshal(m, b)
}
func (m *DeleteProjectMembershipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProjectMembershipRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProjectMembershipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProjectMembershipRequest.Merge(m, src)
}
func (m *DeleteProjectMembershipRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProjectMembershipRequest.Size(m)
}
func (m *DeleteProjectMembershipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProjectMembershipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProjectMembershipRequest proto.InternalMessageInfo

func (m *DeleteProjectMembershipRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *DeleteProjectMembershipRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterEnum("n0stack.iam.v1alpha.ProjectMembership", ProjectMembership_name, ProjectMembership_value)
	proto.RegisterType((*Project)(nil), "n0stack.iam.v1alpha.Project")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.iam.v1alpha.Project.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "n0stack.iam.v1alpha.Project.LabelsEntry")
	proto.RegisterMapType((map[string]ProjectMembership)(nil), "n0stack.iam.v1alpha.Project.MembershipEntry")
	proto.RegisterType((*ListProjectsRequest)(nil), "n0stack.iam.v1alpha.ListProjectsRequest")
	proto.RegisterType((*ListProjectsResponse)(nil), "n0stack.iam.v1alpha.ListProjectsResponse")
	proto.RegisterType((*GetProjectRequest)(nil), "n0stack.iam.v1alpha.GetProjectRequest")
	proto.RegisterType((*CreateProjectRequest)(nil), "n0stack.iam.v1alpha.CreateProjectRequest")
	proto.RegisterType((*UpdateProjectRequest)(nil), "n0stack.iam.v1alpha.UpdateProjectRequest")
	proto.RegisterType((*DeleteProjectRequest)(nil), "n0stack.iam.v1alpha.DeleteProjectRequest")
	proto.RegisterType((*AddProjectMembershipRequest)(nil), "n0stack.iam.v1alpha.AddProjectMembershipRequest")
	proto.RegisterType((*DeleteProjectMembershipRequest)(nil), "n0stack.iam.v1alpha.DeleteProjectMembershipRequest")
}

func init() { proto.RegisterFile("n0stack/iam/v1alpha/project.proto", fileDescriptor_165db4196db99c73) }

var fileDescriptor_165db4196db99c73 = []byte{
	// 877 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x6f, 0x1a, 0x47,
	0x14, 0xef, 0x82, 0x63, 0x9b, 0x87, 0x93, 0x92, 0x09, 0x6d, 0xe9, 0x12, 0x45, 0x30, 0x87, 0x96,
	0xa2, 0xb0, 0x9b, 0x62, 0xa9, 0x72, 0x48, 0xd5, 0x96, 0xd8, 0xeb, 0xd4, 0x91, 0xc1, 0x68, 0xdd,
	0xa8, 0x52, 0x2f, 0x74, 0x80, 0x09, 0x6c, 0xd8, 0x7f, 0xdd, 0x59, 0x5c, 0xa1, 0xc4, 0x97, 0x56,
	0x6a, 0x0f, 0xbd, 0x35, 0x9f, 0xa1, 0xd7, 0x1e, 0x2a, 0xf5, 0x93, 0xf4, 0x2b, 0xf4, 0x83, 0x54,
	0x3b, 0x3b, 0xc0, 0x02, 0x0b, 0xc4, 0x8d, 0x4f, 0x3b, 0x3b, 0xf3, 0x7b, 0xef, 0xfd, 0xe6, 0xcd,
	0xfb, 0xbd, 0x19, 0x28, 0xda, 0x0f, 0x98, 0x4f, 0xba, 0x43, 0xd5, 0x20, 0x96, 0x7a, 0xf1, 0x29,
	0x31, 0xdd, 0x01, 0x51, 0x5d, 0xcf, 0x79, 0x41, 0xbb, 0xbe, 0xe2, 0x7a, 0x8e, 0xef, 0xa0, 0x3b,
	0x02, 0xa2, 0x18, 0xc4, 0x52, 0x04, 0x44, 0xbe, 0xdb, 0x77, 0x9c, 0xbe, 0x49, 0x55, 0xe2, 0x1a,
	0x2a, 0xb1, 0x6d, 0xc7, 0x27, 0xbe, 0xe1, 0xd8, 0x2c, 0x34, 0x91, 0xf3, 0x62, 0x95, 0xff, 0x75,
	0x46, 0xcf, 0x55, 0x6a, 0xb9, 0xfe, 0x58, 0x2c, 0x16, 0x16, 0x17, 0x9f, 0x1b, 0xd4, 0xec, 0xb5,
	0x2d, 0xc2, 0x86, 0x02, 0x71, 0x9f, 0x7f, 0xba, 0x95, 0x3e, 0xb5, 0x2b, 0xec, 0x47, 0xd2, 0xef,
	0x53, 0x4f, 0x75, 0x5c, 0x1e, 0x60, 0x39, 0x18, 0xfe, 0x79, 0x0b, 0x76, 0x5a, 0x21, 0x63, 0x84,
	0x60, 0xcb, 0x26, 0x16, 0xcd, 0x49, 0x05, 0xa9, 0x94, 0xd2, 0xf9, 0x18, 0x9d, 0x41, 0x3a, 0x62,
	0x94, 0x4b, 0x16, 0x92, 0xa5, 0x74, 0xb5, 0xa2, 0xc4, 0xec, 0x4a, 0x11, 0x6e, 0x94, 0xfa, 0x0c,
	0xaf, 0xd9, 0xbe, 0x37, 0xd6, 0xa3, 0x1e, 0xd0, 0x57, 0xb0, 0x6d, 0x92, 0x0e, 0x35, 0x59, 0x6e,
	0x8b, 0xfb, 0x2a, 0xad, 0xf5, 0x75, 0xca, 0xa1, 0xa1, 0x1b, 0x61, 0x87, 0x8a, 0xb0, 0xd7, 0x33,
	0x98, 0x6b, 0x92, 0x71, 0x9b, 0xd3, 0x4d, 0x71, 0xba, 0x69, 0x31, 0xd7, 0x0c, 0x58, 0x9f, 0x02,
	0x58, 0xd4, 0xea, 0x50, 0x8f, 0x0d, 0x0c, 0x37, 0x57, 0xe0, 0x81, 0xee, 0xaf, 0x0d, 0xd4, 0x98,
	0xc2, 0xc3, 0x60, 0x11, 0x7b, 0xf9, 0x0b, 0xc8, 0x2c, 0xee, 0x09, 0x65, 0x20, 0x39, 0xa4, 0x63,
	0x91, 0xaa, 0x60, 0x88, 0xb2, 0x70, 0xe3, 0x82, 0x98, 0x23, 0x9a, 0x4b, 0xf0, 0xb9, 0xf0, 0xa7,
	0x96, 0x38, 0x90, 0xe4, 0x87, 0x90, 0x8e, 0xec, 0xe3, 0x4a, 0xa6, 0x14, 0xde, 0x5d, 0x60, 0x16,
	0x63, 0xfe, 0x79, 0xd4, 0xfc, 0x56, 0xf5, 0xa3, 0x75, 0x1b, 0x9d, 0x79, 0x8b, 0x84, 0xc1, 0xef,
	0xc1, 0x9d, 0x53, 0x83, 0xf9, 0x02, 0xc3, 0x74, 0xfa, 0xc3, 0x88, 0x32, 0x1f, 0xb7, 0x20, 0x3b,
	0x3f, 0xcd, 0x5c, 0xc7, 0x66, 0x14, 0x1d, 0xc0, 0xae, 0xa8, 0x72, 0x96, 0x93, 0x78, 0x72, 0xef,
	0xae, 0x8b, 0xa9, 0x4f, 0xd1, 0xf8, 0x63, 0xb8, 0xfd, 0x84, 0x4e, 0x1c, 0x8a, 0x30, 0x71, 0x75,
	0x87, 0x9b, 0x90, 0x3d, 0xf4, 0x28, 0xf1, 0xe9, 0x02, 0xf6, 0x33, 0xd8, 0x11, 0xce, 0x38, 0x7c,
	0x53, 0xe4, 0x09, 0x18, 0xff, 0x26, 0x41, 0xf6, 0x99, 0xdb, 0xbb, 0x36, 0x87, 0xe8, 0x11, 0xa4,
	0x47, 0xdc, 0x1f, 0xd7, 0x1e, 0x4f, 0x7d, 0xba, 0x2a, 0x2b, 0xa1, 0x3c, 0x95, 0x89, 0x3c, 0x95,
	0xe3, 0x40, 0x9e, 0x0d, 0xc2, 0x86, 0x3a, 0x84, 0xf0, 0x60, 0x8c, 0xcb, 0x90, 0x3d, 0xa2, 0x26,
	0x5d, 0x22, 0x13, 0x97, 0x89, 0x3f, 0x24, 0xc8, 0xd7, 0x7b, 0xbd, 0xe5, 0xf3, 0x13, 0x36, 0x45,
	0xd8, 0x13, 0x9c, 0xda, 0x11, 0xdb, 0xb4, 0x98, 0xe3, 0x72, 0xc8, 0x43, 0x6a, 0xc4, 0xa8, 0x17,
	0xae, 0x87, 0x35, 0xb6, 0x1b, 0x4c, 0xf0, 0xc5, 0xe3, 0x39, 0xad, 0x24, 0xaf, 0x54, 0x42, 0x11,
	0x4b, 0xfc, 0x3d, 0xdc, 0x9b, 0xdb, 0xd3, 0xb5, 0x33, 0x2d, 0x37, 0xe1, 0xf6, 0x92, 0x6f, 0x84,
	0xe1, 0x5e, 0x4b, 0x3f, 0x7b, 0xaa, 0x1d, 0x7e, 0xd3, 0x6e, 0x68, 0x8d, 0xc7, 0x9a, 0x7e, 0xfe,
	0xf5, 0x49, 0xab, 0xfd, 0xac, 0x79, 0xde, 0xd2, 0x0e, 0x4f, 0x8e, 0x4f, 0xb4, 0xa3, 0xcc, 0x3b,
	0x28, 0x05, 0x37, 0xce, 0xbe, 0x6d, 0x6a, 0x7a, 0x46, 0x42, 0x00, 0xdb, 0x21, 0x2c, 0x93, 0xa8,
	0xfe, 0xb9, 0x0b, 0xb7, 0x84, 0xc3, 0x73, 0xea, 0x5d, 0x18, 0x5d, 0x8a, 0x7e, 0x91, 0x60, 0x2f,
	0x5a, 0xf2, 0x28, 0xbe, 0x3d, 0xc5, 0x88, 0x45, 0xfe, 0xe4, 0x0d, 0x90, 0xa1, 0x7e, 0x70, 0xf1,
	0xa7, 0x7f, 0xfe, 0x7d, 0x9d, 0xc8, 0xa3, 0x0f, 0xf9, 0x0d, 0x10, 0x73, 0x79, 0x30, 0xf4, 0x0a,
	0x60, 0x26, 0x14, 0x14, 0x7f, 0x1e, 0x4b, 0x4a, 0x92, 0xd7, 0xd6, 0x2e, 0x2e, 0xf1, 0xb0, 0x18,
	0x15, 0x56, 0x86, 0x55, 0x5f, 0x06, 0x89, 0xbf, 0x44, 0xaf, 0x25, 0xb8, 0x39, 0x27, 0x3f, 0x14,
	0xbf, 0xbb, 0x38, 0x89, 0x6e, 0x20, 0xf1, 0x90, 0x93, 0xd8, 0xc7, 0xa5, 0x35, 0x24, 0x26, 0x57,
	0x28, 0x27, 0x53, 0x9b, 0x4a, 0x2e, 0x60, 0x35, 0xa7, 0xe1, 0x15, 0xac, 0xe2, 0x74, 0xfe, 0x66,
	0xac, 0xe4, 0xff, 0xc1, 0xea, 0x15, 0xdc, 0x9c, 0xab, 0xfb, 0x15, 0xa4, 0xe2, 0xf4, 0x2e, 0xbf,
	0xbf, 0xd4, 0x2f, 0xb4, 0xe0, 0xae, 0x9f, 0x9c, 0x54, 0x79, 0xf3, 0x49, 0xfd, 0x25, 0x41, 0x36,
	0xae, 0x3b, 0xa0, 0x07, 0xb1, 0x2c, 0xd6, 0x34, 0x92, 0x0d, 0x19, 0x7a, 0xca, 0x29, 0x1d, 0xe1,
	0x2f, 0x37, 0x67, 0x88, 0xab, 0xf7, 0x52, 0x9d, 0xf5, 0x06, 0xf5, 0xe5, 0x54, 0xd4, 0x97, 0x35,
	0xa9, 0x8c, 0xfe, 0x96, 0xe0, 0x83, 0x15, 0xbd, 0x02, 0xed, 0x6f, 0xce, 0xde, 0x55, 0xa9, 0x3f,
	0xe1, 0xd4, 0xeb, 0xe5, 0xb7, 0xa5, 0xfe, 0xf8, 0x57, 0xe9, 0xf7, 0x7a, 0x07, 0x1d, 0xc0, 0x8e,
	0x88, 0x86, 0x2b, 0xd3, 0x21, 0xc2, 0x03, 0xdf, 0x77, 0x59, 0x4d, 0x55, 0xfb, 0x86, 0x3f, 0x18,
	0x75, 0x94, 0xae, 0x63, 0xa9, 0x93, 0xe7, 0xa1, 0xf8, 0x96, 0x13, 0x09, 0xa9, 0x9a, 0x21, 0xae,
	0x6b, 0x1a, 0x5d, 0xfe, 0x96, 0x50, 0x5f, 0x30, 0xc7, 0xae, 0x2d, 0xcd, 0x7c, 0x57, 0x08, 0x0c,
	0x14, 0xd2, 0x55, 0x63, 0xde, 0x97, 0x8f, 0x5c, 0x83, 0x58, 0x9d, 0x6d, 0x5e, 0x30, 0xfb, 0xff,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x37, 0x56, 0xc0, 0xa4, 0x82, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectServiceClient interface {
	// あるユーザーがメンバーであるプロジェクトすべてを返す
	// Errors:
	//   NotFound: どのプロジェクトにも属していない場合
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	// Summary: プロジェクトの詳細を取得する
	// Errors:
	//   NotFound: memberじゃない場合
	//   Unauthorized: ログインしていない場合
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*Project, error)
	// ログインしているユーザーがオーナーとなるプロジェクトを作成する
	// Errors:
	//   Unauthorized: ログインしていない場合
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*Project, error)
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AddProjectMembership(ctx context.Context, in *AddProjectMembershipRequest, opts ...grpc.CallOption) (*Project, error)
	DeleteProjectMembership(ctx context.Context, in *DeleteProjectMembershipRequest, opts ...grpc.CallOption) (*Project, error)
}

type projectServiceClient struct {
	cc *grpc.ClientConn
}

func NewProjectServiceClient(cc *grpc.ClientConn) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, "/n0stack.iam.v1alpha.ProjectService/ListProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	out := new(Project)
	err := c.cc.Invoke(ctx, "/n0stack.iam.v1alpha.ProjectService/GetProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	out := new(Project)
	err := c.cc.Invoke(ctx, "/n0stack.iam.v1alpha.ProjectService/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	out := new(Project)
	err := c.cc.Invoke(ctx, "/n0stack.iam.v1alpha.ProjectService/UpdateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/n0stack.iam.v1alpha.ProjectService/DeleteProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AddProjectMembership(ctx context.Context, in *AddProjectMembershipRequest, opts ...grpc.CallOption) (*Project, error) {
	out := new(Project)
	err := c.cc.Invoke(ctx, "/n0stack.iam.v1alpha.ProjectService/AddProjectMembership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DeleteProjectMembership(ctx context.Context, in *DeleteProjectMembershipRequest, opts ...grpc.CallOption) (*Project, error) {
	out := new(Project)
	err := c.cc.Invoke(ctx, "/n0stack.iam.v1alpha.ProjectService/DeleteProjectMembership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
type ProjectServiceServer interface {
	// あるユーザーがメンバーであるプロジェクトすべてを返す
	// Errors:
	//   NotFound: どのプロジェクトにも属していない場合
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	// Summary: プロジェクトの詳細を取得する
	// Errors:
	//   NotFound: memberじゃない場合
	//   Unauthorized: ログインしていない場合
	GetProject(context.Context, *GetProjectRequest) (*Project, error)
	// ログインしているユーザーがオーナーとなるプロジェクトを作成する
	// Errors:
	//   Unauthorized: ログインしていない場合
	CreateProject(context.Context, *CreateProjectRequest) (*Project, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*Project, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*empty.Empty, error)
	AddProjectMembership(context.Context, *AddProjectMembershipRequest) (*Project, error)
	DeleteProjectMembership(context.Context, *DeleteProjectMembershipRequest) (*Project, error)
}

// UnimplementedProjectServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProjectServiceServer struct {
}

func (*UnimplementedProjectServiceServer) ListProjects(ctx context.Context, req *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (*UnimplementedProjectServiceServer) GetProject(ctx context.Context, req *GetProjectRequest) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (*UnimplementedProjectServiceServer) CreateProject(ctx context.Context, req *CreateProjectRequest) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (*UnimplementedProjectServiceServer) UpdateProject(ctx context.Context, req *UpdateProjectRequest) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProject not implemented")
}
func (*UnimplementedProjectServiceServer) DeleteProject(ctx context.Context, req *DeleteProjectRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (*UnimplementedProjectServiceServer) AddProjectMembership(ctx context.Context, req *AddProjectMembershipRequest) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProjectMembership not implemented")
}
func (*UnimplementedProjectServiceServer) DeleteProjectMembership(ctx context.Context, req *DeleteProjectMembershipRequest) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProjectMembership not implemented")
}

func RegisterProjectServiceServer(s *grpc.Server, srv ProjectServiceServer) {
	s.RegisterService(&_ProjectService_serviceDesc, srv)
}

func _ProjectService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.iam.v1alpha.ProjectService/ListProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.iam.v1alpha.ProjectService/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.iam.v1alpha.ProjectService/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.iam.v1alpha.ProjectService/UpdateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProject(ctx, req.(*UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.iam.v1alpha.ProjectService/DeleteProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AddProjectMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AddProjectMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.iam.v1alpha.ProjectService/AddProjectMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AddProjectMembership(ctx, req.(*AddProjectMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DeleteProjectMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DeleteProjectMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n0stack.iam.v1alpha.ProjectService/DeleteProjectMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DeleteProjectMembership(ctx, req.(*DeleteProjectMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "n0stack.iam.v1alpha.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProjects",
			Handler:    _ProjectService_ListProjects_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _ProjectService_GetProject_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _ProjectService_CreateProject_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _ProjectService_UpdateProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _ProjectService_DeleteProject_Handler,
		},
		{
			MethodName: "AddProjectMembership",
			Handler:    _ProjectService_AddProjectMembership_Handler,
		},
		{
			MethodName: "DeleteProjectMembership",
			Handler:    _ProjectService_DeleteProjectMembership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "n0stack/iam/v1alpha/project.proto",
}
