# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from configuration.v0 import ssh_execution_pb2 as configuration_dot_v0_dot_ssh__execution__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SSHExecutionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListSSHExecutions = channel.unary_unary(
        '/n0stack.configuration.SSHExecutionService/ListSSHExecutions',
        request_serializer=configuration_dot_v0_dot_ssh__execution__pb2.ListSSHExecutionsRequest.SerializeToString,
        response_deserializer=configuration_dot_v0_dot_ssh__execution__pb2.ListSSHExecutionsResponse.FromString,
        )
    self.GetSSHExecution = channel.unary_unary(
        '/n0stack.configuration.SSHExecutionService/GetSSHExecution',
        request_serializer=configuration_dot_v0_dot_ssh__execution__pb2.GetSSHExecutionRequest.SerializeToString,
        response_deserializer=configuration_dot_v0_dot_ssh__execution__pb2.SSHExecution.FromString,
        )
    self.ApplySSHExecution = channel.unary_unary(
        '/n0stack.configuration.SSHExecutionService/ApplySSHExecution',
        request_serializer=configuration_dot_v0_dot_ssh__execution__pb2.ApplySSHExecutionRequest.SerializeToString,
        response_deserializer=configuration_dot_v0_dot_ssh__execution__pb2.SSHExecution.FromString,
        )
    self.DeleteSSHExecution = channel.unary_unary(
        '/n0stack.configuration.SSHExecutionService/DeleteSSHExecution',
        request_serializer=configuration_dot_v0_dot_ssh__execution__pb2.DeleteSSHExecutionRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.RunSSHExecution = channel.unary_unary(
        '/n0stack.configuration.SSHExecutionService/RunSSHExecution',
        request_serializer=configuration_dot_v0_dot_ssh__execution__pb2.RunSSHExecutionRequest.SerializeToString,
        response_deserializer=configuration_dot_v0_dot_ssh__execution__pb2.SSHExecutionResult.FromString,
        )


class SSHExecutionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListSSHExecutions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSSHExecution(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ApplySSHExecution(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSSHExecution(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RunSSHExecution(self, request, context):
    """TODO: `returns (stream ...)` looks more good, but stream is not supported by n0cli.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SSHExecutionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListSSHExecutions': grpc.unary_unary_rpc_method_handler(
          servicer.ListSSHExecutions,
          request_deserializer=configuration_dot_v0_dot_ssh__execution__pb2.ListSSHExecutionsRequest.FromString,
          response_serializer=configuration_dot_v0_dot_ssh__execution__pb2.ListSSHExecutionsResponse.SerializeToString,
      ),
      'GetSSHExecution': grpc.unary_unary_rpc_method_handler(
          servicer.GetSSHExecution,
          request_deserializer=configuration_dot_v0_dot_ssh__execution__pb2.GetSSHExecutionRequest.FromString,
          response_serializer=configuration_dot_v0_dot_ssh__execution__pb2.SSHExecution.SerializeToString,
      ),
      'ApplySSHExecution': grpc.unary_unary_rpc_method_handler(
          servicer.ApplySSHExecution,
          request_deserializer=configuration_dot_v0_dot_ssh__execution__pb2.ApplySSHExecutionRequest.FromString,
          response_serializer=configuration_dot_v0_dot_ssh__execution__pb2.SSHExecution.SerializeToString,
      ),
      'DeleteSSHExecution': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSSHExecution,
          request_deserializer=configuration_dot_v0_dot_ssh__execution__pb2.DeleteSSHExecutionRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'RunSSHExecution': grpc.unary_unary_rpc_method_handler(
          servicer.RunSSHExecution,
          request_deserializer=configuration_dot_v0_dot_ssh__execution__pb2.RunSSHExecutionRequest.FromString,
          response_serializer=configuration_dot_v0_dot_ssh__execution__pb2.SSHExecutionResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'n0stack.configuration.SSHExecutionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
